//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A  schema to capture a set of data that is 
 * 			relevant for many exchange documents. It includes information about the 
 * 			file that was created, and high-level information about the data that is 
 * 			being exchanged within the file.
 * 
 * <p>Java class for cs_documentInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_documentInfo">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="documentName" type="{http://www.witsml.org/schemas/1series}nameStruct"/>
 *         <element name="documentAlias" type="{http://www.witsml.org/schemas/1series}nameStruct" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="documentDate" type="{http://www.witsml.org/schemas/1series}timestamp" minOccurs="0"/>
 *         <element name="documentClass" type="{http://www.witsml.org/schemas/1series}nameStruct" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="fileCreationInformation" type="{http://www.witsml.org/schemas/1series}cs_documentFileCreation" minOccurs="0"/>
 *         <element name="securityInformation" type="{http://www.witsml.org/schemas/1series}cs_documentSecurityInfo" maxOccurs="5" minOccurs="0"/>
 *         <element name="disclaimer" type="{http://www.witsml.org/schemas/1series}commentString" minOccurs="0"/>
 *         <element name="auditTrail" type="{http://www.witsml.org/schemas/1series}cs_documentAudit" minOccurs="0"/>
 *         <element name="owner" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="comment" type="{http://www.witsml.org/schemas/1series}commentString" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_documentInfo", propOrder = {
    "documentName",
    "documentAlias",
    "documentDate",
    "documentClass",
    "fileCreationInformation",
    "securityInformation",
    "disclaimer",
    "auditTrail",
    "owner",
    "comment"
})
public class CsDocumentInfo extends com.hashmapinc.tempus.WitsmlObjects.common.CsDocumentInfo {

    @XmlElement(required = true)
    protected NameStruct documentName;
    protected List<NameStruct> documentAlias;
    protected List<NameStruct> documentClass;
    protected CsDocumentFileCreation fileCreationInformation;
    protected List<CsDocumentSecurityInfo> securityInformation;
    protected CsDocumentAudit auditTrail;

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link NameStruct }
     *     
     */
    public NameStruct getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameStruct }
     *     
     */
    public void setDocumentName(NameStruct value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentAlias property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAlias property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getDocumentAlias().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link NameStruct }
     * 
     * 
     */
    public List<NameStruct> getDocumentAlias() {
        if (documentAlias == null) {
            documentAlias = new ArrayList<NameStruct>();
        }
        return this.documentAlias;
    }

    /**
     * Gets the value of the documentClass property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentClass property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getDocumentClass().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link NameStruct }
     * 
     * 
     */
    public List<NameStruct> getDocumentClass() {
        if (documentClass == null) {
            documentClass = new ArrayList<NameStruct>();
        }
        return this.documentClass;
    }

    /**
     * Gets the value of the fileCreationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CsDocumentFileCreation }
     *     
     */
    public CsDocumentFileCreation getFileCreationInformation() {
        return fileCreationInformation;
    }

    /**
     * Sets the value of the fileCreationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsDocumentFileCreation }
     *     
     */
    public void setFileCreationInformation(CsDocumentFileCreation value) {
        this.fileCreationInformation = value;
    }

    /**
     * Gets the value of the securityInformation property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityInformation property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getSecurityInformation().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDocumentSecurityInfo }
     * 
     * 
     */
    public List<CsDocumentSecurityInfo> getSecurityInformation() {
        if (securityInformation == null) {
            securityInformation = new ArrayList<CsDocumentSecurityInfo>();
        }
        return this.securityInformation;
    }

    /**
     * Gets the value of the auditTrail property.
     * 
     * @return
     *     possible object is
     *     {@link CsDocumentAudit }
     *     
     */
    public CsDocumentAudit getAuditTrail() {
        return auditTrail;
    }

    /**
     * Sets the value of the auditTrail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsDocumentAudit }
     *     
     */
    public void setAuditTrail(CsDocumentAudit value) {
        this.auditTrail = value;
    }

}
