//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for cs_drillReportWellTestInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_drillReportWellTestInfo">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="dTim" type="{http://www.witsml.org/schemas/1series}timestamp" minOccurs="0"/>
 *         <element name="testType" type="{http://www.witsml.org/schemas/1series}WellTestType" minOccurs="0"/>
 *         <element name="testNumber" type="{http://www.witsml.org/schemas/1series}positiveCount" minOccurs="0"/>
 *         <element name="mdTop" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="mdBottom" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="tvdTop" type="{http://www.witsml.org/schemas/1series}wellVerticalDepthCoord" minOccurs="0"/>
 *         <element name="tvdBottom" type="{http://www.witsml.org/schemas/1series}wellVerticalDepthCoord" minOccurs="0"/>
 *         <element name="chokeOrificeSize" type="{http://www.witsml.org/schemas/1series}lengthMeasure" minOccurs="0"/>
 *         <element name="densityOil" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="densityWater" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="densityGas" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="flowRateOil" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="flowRateWater" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="flowRateGas" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="presShutIn" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="presFlowing" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="presBottom" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="gasOilRatio" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasure" minOccurs="0"/>
 *         <element name="waterOilRatio" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasure" minOccurs="0"/>
 *         <element name="chloride" type="{http://www.witsml.org/schemas/1series}massConcentrationMeasure" minOccurs="0"/>
 *         <element name="carbonDioxide" type="{http://www.witsml.org/schemas/1series}massConcentrationMeasure" minOccurs="0"/>
 *         <element name="hydrogenSulfide" type="{http://www.witsml.org/schemas/1series}massConcentrationMeasure" minOccurs="0"/>
 *         <element name="volOilTotal" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="volGasTotal" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="volWaterTotal" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="volOilStored" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="extensionNameValue" type="{http://www.witsml.org/schemas/1series}cs_extensionNameValue" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_uid"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_drillReportWellTestInfo", propOrder = {
    "dTim",
    "testType",
    "testNumber",
    "mdTop",
    "mdBottom",
    "tvdTop",
    "tvdBottom",
    "chokeOrificeSize",
    "densityOil",
    "densityWater",
    "densityGas",
    "flowRateOil",
    "flowRateWater",
    "flowRateGas",
    "presShutIn",
    "presFlowing",
    "presBottom",
    "gasOilRatio",
    "waterOilRatio",
    "chloride",
    "carbonDioxide",
    "hydrogenSulfide",
    "volOilTotal",
    "volGasTotal",
    "volWaterTotal",
    "volOilStored",
    "extensionNameValue"
})
public class CsDrillReportWellTestInfo {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dTim;
    @XmlSchemaType(name = "string")
    protected WellTestType testType;
    protected Short testNumber;
    protected MeasuredDepthCoord mdTop;
    protected MeasuredDepthCoord mdBottom;
    protected WellVerticalDepthCoord tvdTop;
    protected WellVerticalDepthCoord tvdBottom;
    protected LengthMeasure chokeOrificeSize;
    protected DensityMeasure densityOil;
    protected DensityMeasure densityWater;
    protected DensityMeasure densityGas;
    protected VolumeFlowRateMeasure flowRateOil;
    protected VolumeFlowRateMeasure flowRateWater;
    protected VolumeFlowRateMeasure flowRateGas;
    protected PressureMeasure presShutIn;
    protected PressureMeasure presFlowing;
    protected PressureMeasure presBottom;
    protected VolumePerVolumeMeasure gasOilRatio;
    protected VolumePerVolumeMeasure waterOilRatio;
    protected MassConcentrationMeasure chloride;
    protected MassConcentrationMeasure carbonDioxide;
    protected MassConcentrationMeasure hydrogenSulfide;
    protected VolumeMeasure volOilTotal;
    protected VolumeMeasure volGasTotal;
    protected VolumeMeasure volWaterTotal;
    protected VolumeMeasure volOilStored;
    protected List<CsExtensionNameValue> extensionNameValue;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the dTim property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDTim() {
        return dTim;
    }

    /**
     * Sets the value of the dTim property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDTim(XMLGregorianCalendar value) {
        this.dTim = value;
    }

    /**
     * Gets the value of the testType property.
     * 
     * @return
     *     possible object is
     *     {@link WellTestType }
     *     
     */
    public WellTestType getTestType() {
        return testType;
    }

    /**
     * Sets the value of the testType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WellTestType }
     *     
     */
    public void setTestType(WellTestType value) {
        this.testType = value;
    }

    /**
     * Gets the value of the testNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getTestNumber() {
        return testNumber;
    }

    /**
     * Sets the value of the testNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setTestNumber(Short value) {
        this.testNumber = value;
    }

    /**
     * Gets the value of the mdTop property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdTop() {
        return mdTop;
    }

    /**
     * Sets the value of the mdTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdTop(MeasuredDepthCoord value) {
        this.mdTop = value;
    }

    /**
     * Gets the value of the mdBottom property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdBottom() {
        return mdBottom;
    }

    /**
     * Sets the value of the mdBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdBottom(MeasuredDepthCoord value) {
        this.mdBottom = value;
    }

    /**
     * Gets the value of the tvdTop property.
     * 
     * @return
     *     possible object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public WellVerticalDepthCoord getTvdTop() {
        return tvdTop;
    }

    /**
     * Sets the value of the tvdTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public void setTvdTop(WellVerticalDepthCoord value) {
        this.tvdTop = value;
    }

    /**
     * Gets the value of the tvdBottom property.
     * 
     * @return
     *     possible object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public WellVerticalDepthCoord getTvdBottom() {
        return tvdBottom;
    }

    /**
     * Sets the value of the tvdBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public void setTvdBottom(WellVerticalDepthCoord value) {
        this.tvdBottom = value;
    }

    /**
     * Gets the value of the chokeOrificeSize property.
     * 
     * @return
     *     possible object is
     *     {@link LengthMeasure }
     *     
     */
    public LengthMeasure getChokeOrificeSize() {
        return chokeOrificeSize;
    }

    /**
     * Sets the value of the chokeOrificeSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthMeasure }
     *     
     */
    public void setChokeOrificeSize(LengthMeasure value) {
        this.chokeOrificeSize = value;
    }

    /**
     * Gets the value of the densityOil property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getDensityOil() {
        return densityOil;
    }

    /**
     * Sets the value of the densityOil property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setDensityOil(DensityMeasure value) {
        this.densityOil = value;
    }

    /**
     * Gets the value of the densityWater property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getDensityWater() {
        return densityWater;
    }

    /**
     * Sets the value of the densityWater property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setDensityWater(DensityMeasure value) {
        this.densityWater = value;
    }

    /**
     * Gets the value of the densityGas property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getDensityGas() {
        return densityGas;
    }

    /**
     * Sets the value of the densityGas property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setDensityGas(DensityMeasure value) {
        this.densityGas = value;
    }

    /**
     * Gets the value of the flowRateOil property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getFlowRateOil() {
        return flowRateOil;
    }

    /**
     * Sets the value of the flowRateOil property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setFlowRateOil(VolumeFlowRateMeasure value) {
        this.flowRateOil = value;
    }

    /**
     * Gets the value of the flowRateWater property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getFlowRateWater() {
        return flowRateWater;
    }

    /**
     * Sets the value of the flowRateWater property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setFlowRateWater(VolumeFlowRateMeasure value) {
        this.flowRateWater = value;
    }

    /**
     * Gets the value of the flowRateGas property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getFlowRateGas() {
        return flowRateGas;
    }

    /**
     * Sets the value of the flowRateGas property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setFlowRateGas(VolumeFlowRateMeasure value) {
        this.flowRateGas = value;
    }

    /**
     * Gets the value of the presShutIn property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPresShutIn() {
        return presShutIn;
    }

    /**
     * Sets the value of the presShutIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPresShutIn(PressureMeasure value) {
        this.presShutIn = value;
    }

    /**
     * Gets the value of the presFlowing property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPresFlowing() {
        return presFlowing;
    }

    /**
     * Sets the value of the presFlowing property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPresFlowing(PressureMeasure value) {
        this.presFlowing = value;
    }

    /**
     * Gets the value of the presBottom property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPresBottom() {
        return presBottom;
    }

    /**
     * Sets the value of the presBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPresBottom(PressureMeasure value) {
        this.presBottom = value;
    }

    /**
     * Gets the value of the gasOilRatio property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasure }
     *     
     */
    public VolumePerVolumeMeasure getGasOilRatio() {
        return gasOilRatio;
    }

    /**
     * Sets the value of the gasOilRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasure }
     *     
     */
    public void setGasOilRatio(VolumePerVolumeMeasure value) {
        this.gasOilRatio = value;
    }

    /**
     * Gets the value of the waterOilRatio property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasure }
     *     
     */
    public VolumePerVolumeMeasure getWaterOilRatio() {
        return waterOilRatio;
    }

    /**
     * Sets the value of the waterOilRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasure }
     *     
     */
    public void setWaterOilRatio(VolumePerVolumeMeasure value) {
        this.waterOilRatio = value;
    }

    /**
     * Gets the value of the chloride property.
     * 
     * @return
     *     possible object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public MassConcentrationMeasure getChloride() {
        return chloride;
    }

    /**
     * Sets the value of the chloride property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public void setChloride(MassConcentrationMeasure value) {
        this.chloride = value;
    }

    /**
     * Gets the value of the carbonDioxide property.
     * 
     * @return
     *     possible object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public MassConcentrationMeasure getCarbonDioxide() {
        return carbonDioxide;
    }

    /**
     * Sets the value of the carbonDioxide property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public void setCarbonDioxide(MassConcentrationMeasure value) {
        this.carbonDioxide = value;
    }

    /**
     * Gets the value of the hydrogenSulfide property.
     * 
     * @return
     *     possible object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public MassConcentrationMeasure getHydrogenSulfide() {
        return hydrogenSulfide;
    }

    /**
     * Sets the value of the hydrogenSulfide property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassConcentrationMeasure }
     *     
     */
    public void setHydrogenSulfide(MassConcentrationMeasure value) {
        this.hydrogenSulfide = value;
    }

    /**
     * Gets the value of the volOilTotal property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getVolOilTotal() {
        return volOilTotal;
    }

    /**
     * Sets the value of the volOilTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setVolOilTotal(VolumeMeasure value) {
        this.volOilTotal = value;
    }

    /**
     * Gets the value of the volGasTotal property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getVolGasTotal() {
        return volGasTotal;
    }

    /**
     * Sets the value of the volGasTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setVolGasTotal(VolumeMeasure value) {
        this.volGasTotal = value;
    }

    /**
     * Gets the value of the volWaterTotal property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getVolWaterTotal() {
        return volWaterTotal;
    }

    /**
     * Sets the value of the volWaterTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setVolWaterTotal(VolumeMeasure value) {
        this.volWaterTotal = value;
    }

    /**
     * Gets the value of the volOilStored property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getVolOilStored() {
        return volOilStored;
    }

    /**
     * Sets the value of the volOilStored property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setVolOilStored(VolumeMeasure value) {
        this.volOilStored = value;
    }

    /**
     * Gets the value of the extensionNameValue property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNameValue property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getExtensionNameValue().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsExtensionNameValue }
     * 
     * 
     */
    public List<CsExtensionNameValue> getExtensionNameValue() {
        if (extensionNameValue == null) {
            extensionNameValue = new ArrayList<CsExtensionNameValue>();
        }
        return this.extensionNameValue;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
