//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cs_localCRS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_localCRS">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <choice>
 *           <element name="usesWellAsOrigin" type="{http://www.witsml.org/schemas/1series}logicalBoolean"/>
 *           <element name="origin" type="{http://www.witsml.org/schemas/1series}refNameString"/>
 *           <element name="originDescription" type="{http://www.witsml.org/schemas/1series}commentString"/>
 *         </choice>
 *         <element name="yAxisAzimuth" type="{http://www.witsml.org/schemas/1series}yAxisAzimuth" minOccurs="0"/>
 *         <element name="magneticDeclination" type="{http://www.witsml.org/schemas/1series}planeAngleMeasure" minOccurs="0"/>
 *         <element name="gridConvergence" type="{http://www.witsml.org/schemas/1series}planeAngleMeasure" minOccurs="0"/>
 *         <element name="yAxisDescription" type="{http://www.witsml.org/schemas/1series}commentString" minOccurs="0"/>
 *         <element name="xRotationCounterClockwise" type="{http://www.witsml.org/schemas/1series}logicalBoolean" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_localCRS", propOrder = {
    "usesWellAsOrigin",
    "origin",
    "originDescription",
    "yAxisAzimuth",
    "magneticDeclination",
    "gridConvergence",
    "yAxisDescription",
    "xRotationCounterClockwise"
})
public class CsLocalCRS {

    protected Boolean usesWellAsOrigin;
    protected RefNameString origin;
    protected String originDescription;
    protected YAxisAzimuth yAxisAzimuth;
    protected PlaneAngleMeasure magneticDeclination;
    protected PlaneAngleMeasure gridConvergence;
    protected String yAxisDescription;
    protected Boolean xRotationCounterClockwise;

    /**
     * Gets the value of the usesWellAsOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUsesWellAsOrigin() {
        return usesWellAsOrigin;
    }

    /**
     * Sets the value of the usesWellAsOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesWellAsOrigin(Boolean value) {
        this.usesWellAsOrigin = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link RefNameString }
     *     
     */
    public RefNameString getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefNameString }
     *     
     */
    public void setOrigin(RefNameString value) {
        this.origin = value;
    }

    /**
     * Gets the value of the originDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginDescription() {
        return originDescription;
    }

    /**
     * Sets the value of the originDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginDescription(String value) {
        this.originDescription = value;
    }

    /**
     * Gets the value of the yAxisAzimuth property.
     * 
     * @return
     *     possible object is
     *     {@link YAxisAzimuth }
     *     
     */
    public YAxisAzimuth getYAxisAzimuth() {
        return yAxisAzimuth;
    }

    /**
     * Sets the value of the yAxisAzimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link YAxisAzimuth }
     *     
     */
    public void setYAxisAzimuth(YAxisAzimuth value) {
        this.yAxisAzimuth = value;
    }

    /**
     * Gets the value of the magneticDeclination property.
     * 
     * @return
     *     possible object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public PlaneAngleMeasure getMagneticDeclination() {
        return magneticDeclination;
    }

    /**
     * Sets the value of the magneticDeclination property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public void setMagneticDeclination(PlaneAngleMeasure value) {
        this.magneticDeclination = value;
    }

    /**
     * Gets the value of the gridConvergence property.
     * 
     * @return
     *     possible object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public PlaneAngleMeasure getGridConvergence() {
        return gridConvergence;
    }

    /**
     * Sets the value of the gridConvergence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public void setGridConvergence(PlaneAngleMeasure value) {
        this.gridConvergence = value;
    }

    /**
     * Gets the value of the yAxisDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisDescription() {
        return yAxisDescription;
    }

    /**
     * Sets the value of the yAxisDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisDescription(String value) {
        this.yAxisDescription = value;
    }

    /**
     * Gets the value of the xRotationCounterClockwise property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXRotationCounterClockwise() {
        return xRotationCounterClockwise;
    }

    /**
     * Sets the value of the xRotationCounterClockwise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXRotationCounterClockwise(Boolean value) {
        this.xRotationCounterClockwise = value;
    }

}
