//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about a set of perforations.  
 * 			The assumption is that all perforations within a given
 * 			set are created with the same device or method.
 * 			
 * 
 * <p>Java class for cs_stimPerforationSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_stimPerforationSet">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="type" type="{http://www.witsml.org/schemas/1series}str32" minOccurs="0"/>
 *         <element name="mdPerforationsTop" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="mdPerforationsBottom" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="tvdPerforationsTop" type="{http://www.witsml.org/schemas/1series}wellVerticalDepthCoord" minOccurs="0"/>
 *         <element name="tvdPerforationsBottom" type="{http://www.witsml.org/schemas/1series}wellVerticalDepthCoord" minOccurs="0"/>
 *         <element name="perforationCount" type="{http://www.witsml.org/schemas/1series}nonNegativeCount" minOccurs="0"/>
 *         <element name="size" type="{http://www.witsml.org/schemas/1series}lengthMeasure" minOccurs="0"/>
 *         <element name="densityPerforation" type="{http://www.witsml.org/schemas/1series}perLengthMeasure" minOccurs="0"/>
 *         <element name="phasingPerforation" type="{http://www.witsml.org/schemas/1series}planeAngleMeasure" minOccurs="0"/>
 *         <element name="frictionFactor" type="{http://www.witsml.org/schemas/1series}unitlessQuantity" minOccurs="0"/>
 *         <element name="frictionPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="dischargeCoefficient" type="{http://www.witsml.org/schemas/1series}unitlessQuantity" minOccurs="0"/>
 *         <element name="extensionNameValue" type="{http://www.witsml.org/schemas/1series}cs_extensionNameValue" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_uid"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_stimPerforationSet", propOrder = {
    "type",
    "mdPerforationsTop",
    "mdPerforationsBottom",
    "tvdPerforationsTop",
    "tvdPerforationsBottom",
    "perforationCount",
    "size",
    "densityPerforation",
    "phasingPerforation",
    "frictionFactor",
    "frictionPres",
    "dischargeCoefficient",
    "extensionNameValue"
})
public class CsStimPerforationSet {

    protected String type;
    protected MeasuredDepthCoord mdPerforationsTop;
    protected MeasuredDepthCoord mdPerforationsBottom;
    protected WellVerticalDepthCoord tvdPerforationsTop;
    protected WellVerticalDepthCoord tvdPerforationsBottom;
    protected Short perforationCount;
    protected LengthMeasure size;
    protected PerLengthMeasure densityPerforation;
    protected PlaneAngleMeasure phasingPerforation;
    protected Double frictionFactor;
    protected PressureMeasure frictionPres;
    protected Double dischargeCoefficient;
    protected List<CsExtensionNameValue> extensionNameValue;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the mdPerforationsTop property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdPerforationsTop() {
        return mdPerforationsTop;
    }

    /**
     * Sets the value of the mdPerforationsTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdPerforationsTop(MeasuredDepthCoord value) {
        this.mdPerforationsTop = value;
    }

    /**
     * Gets the value of the mdPerforationsBottom property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdPerforationsBottom() {
        return mdPerforationsBottom;
    }

    /**
     * Sets the value of the mdPerforationsBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdPerforationsBottom(MeasuredDepthCoord value) {
        this.mdPerforationsBottom = value;
    }

    /**
     * Gets the value of the tvdPerforationsTop property.
     * 
     * @return
     *     possible object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public WellVerticalDepthCoord getTvdPerforationsTop() {
        return tvdPerforationsTop;
    }

    /**
     * Sets the value of the tvdPerforationsTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public void setTvdPerforationsTop(WellVerticalDepthCoord value) {
        this.tvdPerforationsTop = value;
    }

    /**
     * Gets the value of the tvdPerforationsBottom property.
     * 
     * @return
     *     possible object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public WellVerticalDepthCoord getTvdPerforationsBottom() {
        return tvdPerforationsBottom;
    }

    /**
     * Sets the value of the tvdPerforationsBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link WellVerticalDepthCoord }
     *     
     */
    public void setTvdPerforationsBottom(WellVerticalDepthCoord value) {
        this.tvdPerforationsBottom = value;
    }

    /**
     * Gets the value of the perforationCount property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPerforationCount() {
        return perforationCount;
    }

    /**
     * Sets the value of the perforationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPerforationCount(Short value) {
        this.perforationCount = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link LengthMeasure }
     *     
     */
    public LengthMeasure getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthMeasure }
     *     
     */
    public void setSize(LengthMeasure value) {
        this.size = value;
    }

    /**
     * Gets the value of the densityPerforation property.
     * 
     * @return
     *     possible object is
     *     {@link PerLengthMeasure }
     *     
     */
    public PerLengthMeasure getDensityPerforation() {
        return densityPerforation;
    }

    /**
     * Sets the value of the densityPerforation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerLengthMeasure }
     *     
     */
    public void setDensityPerforation(PerLengthMeasure value) {
        this.densityPerforation = value;
    }

    /**
     * Gets the value of the phasingPerforation property.
     * 
     * @return
     *     possible object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public PlaneAngleMeasure getPhasingPerforation() {
        return phasingPerforation;
    }

    /**
     * Sets the value of the phasingPerforation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaneAngleMeasure }
     *     
     */
    public void setPhasingPerforation(PlaneAngleMeasure value) {
        this.phasingPerforation = value;
    }

    /**
     * Gets the value of the frictionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFrictionFactor() {
        return frictionFactor;
    }

    /**
     * Sets the value of the frictionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFrictionFactor(Double value) {
        this.frictionFactor = value;
    }

    /**
     * Gets the value of the frictionPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getFrictionPres() {
        return frictionPres;
    }

    /**
     * Sets the value of the frictionPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setFrictionPres(PressureMeasure value) {
        this.frictionPres = value;
    }

    /**
     * Gets the value of the dischargeCoefficient property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDischargeCoefficient() {
        return dischargeCoefficient;
    }

    /**
     * Sets the value of the dischargeCoefficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDischargeCoefficient(Double value) {
        this.dischargeCoefficient = value;
    }

    /**
     * Gets the value of the extensionNameValue property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNameValue property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getExtensionNameValue().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsExtensionNameValue }
     * 
     * 
     */
    public List<CsExtensionNameValue> getExtensionNameValue() {
        if (extensionNameValue == null) {
            extensionNameValue = new ArrayList<CsExtensionNameValue>();
        }
        return this.extensionNameValue;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
