//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * WITSML - the flow path for a well stimulation job.
 * 
 * <p>Java class for cs_stimFlowPath complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_stimFlowPath">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="kind" type="{http://www.witsml.org/schemas/1series}StimStageFlowPathType"/>
 *         <element name="name" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="description" type="{http://www.witsml.org/schemas/1series}descriptionString" minOccurs="0"/>
 *         <element name="maxTreatmentPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="maxSlurryRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxWellheadRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxN2StdRate" type="{http://www.witsml.org/schemas/1series}standardVolumePerTimeMeasure" minOccurs="0"/>
 *         <element name="maxCO2LiquidRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxGelRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxOilRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxAcidRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="maxPropConc" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="maxSlurryPropConc" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="avgTreatPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="avgBaseFluidRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgSlurryRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgWellheadRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgN2StdRate" type="{http://www.witsml.org/schemas/1series}standardVolumePerTimeMeasure" minOccurs="0"/>
 *         <element name="avgCO2LiquidRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgGelRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgOilRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgAcidRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="avgPropConc" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="avgSlurryPropConc" type="{http://www.witsml.org/schemas/1series}densityMeasure" minOccurs="0"/>
 *         <element name="avgTemperature" type="{http://www.witsml.org/schemas/1series}thermodynamicTemperatureMeasure" minOccurs="0"/>
 *         <element name="avgIntervalPhaseFraction" type="{http://www.witsml.org/schemas/1series}nonNegativeCount" minOccurs="0"/>
 *         <element name="avgBaseFluidQuality" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="avgN2BaseFluidQuality" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="avgCO2BaseFluidQuality" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="avgHydraulicPower" type="{http://www.witsml.org/schemas/1series}powerMeasure" minOccurs="0"/>
 *         <element name="baseFluidVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="slurryVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="wellheadVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="stdVolN2" type="{http://www.witsml.org/schemas/1series}standardVolumeMeasure" minOccurs="0"/>
 *         <element name="massCO2" type="{http://www.witsml.org/schemas/1series}massMeasure" minOccurs="0"/>
 *         <element name="gelVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="oilVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="acidVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="baseFluidBypassVol" type="{http://www.witsml.org/schemas/1series}volumeMeasure" minOccurs="0"/>
 *         <element name="propMass" type="{http://www.witsml.org/schemas/1series}massMeasure" minOccurs="0"/>
 *         <element name="maxPmaxPacPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="maxPmaxWeaklinkPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="avgPmaxPacPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="avgPmaxWeaklinkPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="shutinPres5Min" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="shutinPres10Min" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="shutinPres15Min" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="breakDownPres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="percentPad" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="fractureGradient" type="{http://www.witsml.org/schemas/1series}forcePerVolumeMeasure" minOccurs="0"/>
 *         <element name="pipeFrictionFactor" type="{http://www.witsml.org/schemas/1series}unitlessQuantity" minOccurs="0"/>
 *         <element name="stageCount" type="{http://www.witsml.org/schemas/1series}nonNegativeCount" minOccurs="0"/>
 *         <element name="tubular" type="{http://www.witsml.org/schemas/1series}cs_stimTubular" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="jobStage" type="{http://www.witsml.org/schemas/1series}cs_stimJobStage" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="jobEvent" type="{http://www.witsml.org/schemas/1series}cs_stimEvent" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="extensionNameValue" type="{http://www.witsml.org/schemas/1series}cs_extensionNameValue" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_uid"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_stimFlowPath", propOrder = {
    "kind",
    "name",
    "description",
    "maxTreatmentPres",
    "maxSlurryRate",
    "maxWellheadRate",
    "maxN2StdRate",
    "maxCO2LiquidRate",
    "maxGelRate",
    "maxOilRate",
    "maxAcidRate",
    "maxPropConc",
    "maxSlurryPropConc",
    "avgTreatPres",
    "avgBaseFluidRate",
    "avgSlurryRate",
    "avgWellheadRate",
    "avgN2StdRate",
    "avgCO2LiquidRate",
    "avgGelRate",
    "avgOilRate",
    "avgAcidRate",
    "avgPropConc",
    "avgSlurryPropConc",
    "avgTemperature",
    "avgIntervalPhaseFraction",
    "avgBaseFluidQuality",
    "avgN2BaseFluidQuality",
    "avgCO2BaseFluidQuality",
    "avgHydraulicPower",
    "baseFluidVol",
    "slurryVol",
    "wellheadVol",
    "stdVolN2",
    "massCO2",
    "gelVol",
    "oilVol",
    "acidVol",
    "baseFluidBypassVol",
    "propMass",
    "maxPmaxPacPres",
    "maxPmaxWeaklinkPres",
    "avgPmaxPacPres",
    "avgPmaxWeaklinkPres",
    "shutinPres5Min",
    "shutinPres10Min",
    "shutinPres15Min",
    "breakDownPres",
    "percentPad",
    "fractureGradient",
    "pipeFrictionFactor",
    "stageCount",
    "tubular",
    "jobStage",
    "jobEvent",
    "extensionNameValue"
})
public class CsStimFlowPath {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StimStageFlowPathType kind;
    protected String name;
    protected String description;
    protected PressureMeasure maxTreatmentPres;
    protected VolumeFlowRateMeasure maxSlurryRate;
    protected VolumeFlowRateMeasure maxWellheadRate;
    protected StandardVolumePerTimeMeasure maxN2StdRate;
    protected VolumeFlowRateMeasure maxCO2LiquidRate;
    protected VolumeFlowRateMeasure maxGelRate;
    protected VolumeFlowRateMeasure maxOilRate;
    protected VolumeFlowRateMeasure maxAcidRate;
    protected DensityMeasure maxPropConc;
    protected DensityMeasure maxSlurryPropConc;
    protected PressureMeasure avgTreatPres;
    protected VolumeFlowRateMeasure avgBaseFluidRate;
    protected VolumeFlowRateMeasure avgSlurryRate;
    protected VolumeFlowRateMeasure avgWellheadRate;
    protected StandardVolumePerTimeMeasure avgN2StdRate;
    protected VolumeFlowRateMeasure avgCO2LiquidRate;
    protected VolumeFlowRateMeasure avgGelRate;
    protected VolumeFlowRateMeasure avgOilRate;
    protected VolumeFlowRateMeasure avgAcidRate;
    protected DensityMeasure avgPropConc;
    protected DensityMeasure avgSlurryPropConc;
    protected ThermodynamicTemperatureMeasure avgTemperature;
    protected Short avgIntervalPhaseFraction;
    protected VolumePerVolumeMeasurePercent avgBaseFluidQuality;
    protected VolumePerVolumeMeasurePercent avgN2BaseFluidQuality;
    protected VolumePerVolumeMeasurePercent avgCO2BaseFluidQuality;
    protected PowerMeasure avgHydraulicPower;
    protected VolumeMeasure baseFluidVol;
    protected VolumeMeasure slurryVol;
    protected VolumeMeasure wellheadVol;
    protected StandardVolumeMeasure stdVolN2;
    protected MassMeasure massCO2;
    protected VolumeMeasure gelVol;
    protected VolumeMeasure oilVol;
    protected VolumeMeasure acidVol;
    protected VolumeMeasure baseFluidBypassVol;
    protected MassMeasure propMass;
    protected PressureMeasure maxPmaxPacPres;
    protected PressureMeasure maxPmaxWeaklinkPres;
    protected PressureMeasure avgPmaxPacPres;
    protected PressureMeasure avgPmaxWeaklinkPres;
    protected PressureMeasure shutinPres5Min;
    protected PressureMeasure shutinPres10Min;
    protected PressureMeasure shutinPres15Min;
    protected PressureMeasure breakDownPres;
    protected VolumePerVolumeMeasurePercent percentPad;
    protected ForcePerVolumeMeasure fractureGradient;
    protected Double pipeFrictionFactor;
    protected Short stageCount;
    protected List<CsStimTubular> tubular;
    protected List<CsStimJobStage> jobStage;
    protected List<CsStimEvent> jobEvent;
    protected List<CsExtensionNameValue> extensionNameValue;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link StimStageFlowPathType }
     *     
     */
    public StimStageFlowPathType getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link StimStageFlowPathType }
     *     
     */
    public void setKind(StimStageFlowPathType value) {
        this.kind = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the maxTreatmentPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getMaxTreatmentPres() {
        return maxTreatmentPres;
    }

    /**
     * Sets the value of the maxTreatmentPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setMaxTreatmentPres(PressureMeasure value) {
        this.maxTreatmentPres = value;
    }

    /**
     * Gets the value of the maxSlurryRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxSlurryRate() {
        return maxSlurryRate;
    }

    /**
     * Sets the value of the maxSlurryRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxSlurryRate(VolumeFlowRateMeasure value) {
        this.maxSlurryRate = value;
    }

    /**
     * Gets the value of the maxWellheadRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxWellheadRate() {
        return maxWellheadRate;
    }

    /**
     * Sets the value of the maxWellheadRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxWellheadRate(VolumeFlowRateMeasure value) {
        this.maxWellheadRate = value;
    }

    /**
     * Gets the value of the maxN2StdRate property.
     * 
     * @return
     *     possible object is
     *     {@link StandardVolumePerTimeMeasure }
     *     
     */
    public StandardVolumePerTimeMeasure getMaxN2StdRate() {
        return maxN2StdRate;
    }

    /**
     * Sets the value of the maxN2StdRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardVolumePerTimeMeasure }
     *     
     */
    public void setMaxN2StdRate(StandardVolumePerTimeMeasure value) {
        this.maxN2StdRate = value;
    }

    /**
     * Gets the value of the maxCO2LiquidRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxCO2LiquidRate() {
        return maxCO2LiquidRate;
    }

    /**
     * Sets the value of the maxCO2LiquidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxCO2LiquidRate(VolumeFlowRateMeasure value) {
        this.maxCO2LiquidRate = value;
    }

    /**
     * Gets the value of the maxGelRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxGelRate() {
        return maxGelRate;
    }

    /**
     * Sets the value of the maxGelRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxGelRate(VolumeFlowRateMeasure value) {
        this.maxGelRate = value;
    }

    /**
     * Gets the value of the maxOilRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxOilRate() {
        return maxOilRate;
    }

    /**
     * Sets the value of the maxOilRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxOilRate(VolumeFlowRateMeasure value) {
        this.maxOilRate = value;
    }

    /**
     * Gets the value of the maxAcidRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getMaxAcidRate() {
        return maxAcidRate;
    }

    /**
     * Sets the value of the maxAcidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setMaxAcidRate(VolumeFlowRateMeasure value) {
        this.maxAcidRate = value;
    }

    /**
     * Gets the value of the maxPropConc property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getMaxPropConc() {
        return maxPropConc;
    }

    /**
     * Sets the value of the maxPropConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setMaxPropConc(DensityMeasure value) {
        this.maxPropConc = value;
    }

    /**
     * Gets the value of the maxSlurryPropConc property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getMaxSlurryPropConc() {
        return maxSlurryPropConc;
    }

    /**
     * Sets the value of the maxSlurryPropConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setMaxSlurryPropConc(DensityMeasure value) {
        this.maxSlurryPropConc = value;
    }

    /**
     * Gets the value of the avgTreatPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getAvgTreatPres() {
        return avgTreatPres;
    }

    /**
     * Sets the value of the avgTreatPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setAvgTreatPres(PressureMeasure value) {
        this.avgTreatPres = value;
    }

    /**
     * Gets the value of the avgBaseFluidRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgBaseFluidRate() {
        return avgBaseFluidRate;
    }

    /**
     * Sets the value of the avgBaseFluidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgBaseFluidRate(VolumeFlowRateMeasure value) {
        this.avgBaseFluidRate = value;
    }

    /**
     * Gets the value of the avgSlurryRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgSlurryRate() {
        return avgSlurryRate;
    }

    /**
     * Sets the value of the avgSlurryRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgSlurryRate(VolumeFlowRateMeasure value) {
        this.avgSlurryRate = value;
    }

    /**
     * Gets the value of the avgWellheadRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgWellheadRate() {
        return avgWellheadRate;
    }

    /**
     * Sets the value of the avgWellheadRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgWellheadRate(VolumeFlowRateMeasure value) {
        this.avgWellheadRate = value;
    }

    /**
     * Gets the value of the avgN2StdRate property.
     * 
     * @return
     *     possible object is
     *     {@link StandardVolumePerTimeMeasure }
     *     
     */
    public StandardVolumePerTimeMeasure getAvgN2StdRate() {
        return avgN2StdRate;
    }

    /**
     * Sets the value of the avgN2StdRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardVolumePerTimeMeasure }
     *     
     */
    public void setAvgN2StdRate(StandardVolumePerTimeMeasure value) {
        this.avgN2StdRate = value;
    }

    /**
     * Gets the value of the avgCO2LiquidRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgCO2LiquidRate() {
        return avgCO2LiquidRate;
    }

    /**
     * Sets the value of the avgCO2LiquidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgCO2LiquidRate(VolumeFlowRateMeasure value) {
        this.avgCO2LiquidRate = value;
    }

    /**
     * Gets the value of the avgGelRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgGelRate() {
        return avgGelRate;
    }

    /**
     * Sets the value of the avgGelRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgGelRate(VolumeFlowRateMeasure value) {
        this.avgGelRate = value;
    }

    /**
     * Gets the value of the avgOilRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgOilRate() {
        return avgOilRate;
    }

    /**
     * Sets the value of the avgOilRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgOilRate(VolumeFlowRateMeasure value) {
        this.avgOilRate = value;
    }

    /**
     * Gets the value of the avgAcidRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getAvgAcidRate() {
        return avgAcidRate;
    }

    /**
     * Sets the value of the avgAcidRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setAvgAcidRate(VolumeFlowRateMeasure value) {
        this.avgAcidRate = value;
    }

    /**
     * Gets the value of the avgPropConc property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getAvgPropConc() {
        return avgPropConc;
    }

    /**
     * Sets the value of the avgPropConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setAvgPropConc(DensityMeasure value) {
        this.avgPropConc = value;
    }

    /**
     * Gets the value of the avgSlurryPropConc property.
     * 
     * @return
     *     possible object is
     *     {@link DensityMeasure }
     *     
     */
    public DensityMeasure getAvgSlurryPropConc() {
        return avgSlurryPropConc;
    }

    /**
     * Sets the value of the avgSlurryPropConc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityMeasure }
     *     
     */
    public void setAvgSlurryPropConc(DensityMeasure value) {
        this.avgSlurryPropConc = value;
    }

    /**
     * Gets the value of the avgTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link ThermodynamicTemperatureMeasure }
     *     
     */
    public ThermodynamicTemperatureMeasure getAvgTemperature() {
        return avgTemperature;
    }

    /**
     * Sets the value of the avgTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThermodynamicTemperatureMeasure }
     *     
     */
    public void setAvgTemperature(ThermodynamicTemperatureMeasure value) {
        this.avgTemperature = value;
    }

    /**
     * Gets the value of the avgIntervalPhaseFraction property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAvgIntervalPhaseFraction() {
        return avgIntervalPhaseFraction;
    }

    /**
     * Sets the value of the avgIntervalPhaseFraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAvgIntervalPhaseFraction(Short value) {
        this.avgIntervalPhaseFraction = value;
    }

    /**
     * Gets the value of the avgBaseFluidQuality property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getAvgBaseFluidQuality() {
        return avgBaseFluidQuality;
    }

    /**
     * Sets the value of the avgBaseFluidQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setAvgBaseFluidQuality(VolumePerVolumeMeasurePercent value) {
        this.avgBaseFluidQuality = value;
    }

    /**
     * Gets the value of the avgN2BaseFluidQuality property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getAvgN2BaseFluidQuality() {
        return avgN2BaseFluidQuality;
    }

    /**
     * Sets the value of the avgN2BaseFluidQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setAvgN2BaseFluidQuality(VolumePerVolumeMeasurePercent value) {
        this.avgN2BaseFluidQuality = value;
    }

    /**
     * Gets the value of the avgCO2BaseFluidQuality property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getAvgCO2BaseFluidQuality() {
        return avgCO2BaseFluidQuality;
    }

    /**
     * Sets the value of the avgCO2BaseFluidQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setAvgCO2BaseFluidQuality(VolumePerVolumeMeasurePercent value) {
        this.avgCO2BaseFluidQuality = value;
    }

    /**
     * Gets the value of the avgHydraulicPower property.
     * 
     * @return
     *     possible object is
     *     {@link PowerMeasure }
     *     
     */
    public PowerMeasure getAvgHydraulicPower() {
        return avgHydraulicPower;
    }

    /**
     * Sets the value of the avgHydraulicPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowerMeasure }
     *     
     */
    public void setAvgHydraulicPower(PowerMeasure value) {
        this.avgHydraulicPower = value;
    }

    /**
     * Gets the value of the baseFluidVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getBaseFluidVol() {
        return baseFluidVol;
    }

    /**
     * Sets the value of the baseFluidVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setBaseFluidVol(VolumeMeasure value) {
        this.baseFluidVol = value;
    }

    /**
     * Gets the value of the slurryVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getSlurryVol() {
        return slurryVol;
    }

    /**
     * Sets the value of the slurryVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setSlurryVol(VolumeMeasure value) {
        this.slurryVol = value;
    }

    /**
     * Gets the value of the wellheadVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getWellheadVol() {
        return wellheadVol;
    }

    /**
     * Sets the value of the wellheadVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setWellheadVol(VolumeMeasure value) {
        this.wellheadVol = value;
    }

    /**
     * Gets the value of the stdVolN2 property.
     * 
     * @return
     *     possible object is
     *     {@link StandardVolumeMeasure }
     *     
     */
    public StandardVolumeMeasure getStdVolN2() {
        return stdVolN2;
    }

    /**
     * Sets the value of the stdVolN2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardVolumeMeasure }
     *     
     */
    public void setStdVolN2(StandardVolumeMeasure value) {
        this.stdVolN2 = value;
    }

    /**
     * Gets the value of the massCO2 property.
     * 
     * @return
     *     possible object is
     *     {@link MassMeasure }
     *     
     */
    public MassMeasure getMassCO2() {
        return massCO2;
    }

    /**
     * Sets the value of the massCO2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassMeasure }
     *     
     */
    public void setMassCO2(MassMeasure value) {
        this.massCO2 = value;
    }

    /**
     * Gets the value of the gelVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getGelVol() {
        return gelVol;
    }

    /**
     * Sets the value of the gelVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setGelVol(VolumeMeasure value) {
        this.gelVol = value;
    }

    /**
     * Gets the value of the oilVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getOilVol() {
        return oilVol;
    }

    /**
     * Sets the value of the oilVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setOilVol(VolumeMeasure value) {
        this.oilVol = value;
    }

    /**
     * Gets the value of the acidVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getAcidVol() {
        return acidVol;
    }

    /**
     * Sets the value of the acidVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setAcidVol(VolumeMeasure value) {
        this.acidVol = value;
    }

    /**
     * Gets the value of the baseFluidBypassVol property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeMeasure }
     *     
     */
    public VolumeMeasure getBaseFluidBypassVol() {
        return baseFluidBypassVol;
    }

    /**
     * Sets the value of the baseFluidBypassVol property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeMeasure }
     *     
     */
    public void setBaseFluidBypassVol(VolumeMeasure value) {
        this.baseFluidBypassVol = value;
    }

    /**
     * Gets the value of the propMass property.
     * 
     * @return
     *     possible object is
     *     {@link MassMeasure }
     *     
     */
    public MassMeasure getPropMass() {
        return propMass;
    }

    /**
     * Sets the value of the propMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassMeasure }
     *     
     */
    public void setPropMass(MassMeasure value) {
        this.propMass = value;
    }

    /**
     * Gets the value of the maxPmaxPacPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getMaxPmaxPacPres() {
        return maxPmaxPacPres;
    }

    /**
     * Sets the value of the maxPmaxPacPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setMaxPmaxPacPres(PressureMeasure value) {
        this.maxPmaxPacPres = value;
    }

    /**
     * Gets the value of the maxPmaxWeaklinkPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getMaxPmaxWeaklinkPres() {
        return maxPmaxWeaklinkPres;
    }

    /**
     * Sets the value of the maxPmaxWeaklinkPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setMaxPmaxWeaklinkPres(PressureMeasure value) {
        this.maxPmaxWeaklinkPres = value;
    }

    /**
     * Gets the value of the avgPmaxPacPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getAvgPmaxPacPres() {
        return avgPmaxPacPres;
    }

    /**
     * Sets the value of the avgPmaxPacPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setAvgPmaxPacPres(PressureMeasure value) {
        this.avgPmaxPacPres = value;
    }

    /**
     * Gets the value of the avgPmaxWeaklinkPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getAvgPmaxWeaklinkPres() {
        return avgPmaxWeaklinkPres;
    }

    /**
     * Sets the value of the avgPmaxWeaklinkPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setAvgPmaxWeaklinkPres(PressureMeasure value) {
        this.avgPmaxWeaklinkPres = value;
    }

    /**
     * Gets the value of the shutinPres5Min property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getShutinPres5Min() {
        return shutinPres5Min;
    }

    /**
     * Sets the value of the shutinPres5Min property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setShutinPres5Min(PressureMeasure value) {
        this.shutinPres5Min = value;
    }

    /**
     * Gets the value of the shutinPres10Min property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getShutinPres10Min() {
        return shutinPres10Min;
    }

    /**
     * Sets the value of the shutinPres10Min property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setShutinPres10Min(PressureMeasure value) {
        this.shutinPres10Min = value;
    }

    /**
     * Gets the value of the shutinPres15Min property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getShutinPres15Min() {
        return shutinPres15Min;
    }

    /**
     * Sets the value of the shutinPres15Min property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setShutinPres15Min(PressureMeasure value) {
        this.shutinPres15Min = value;
    }

    /**
     * Gets the value of the breakDownPres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getBreakDownPres() {
        return breakDownPres;
    }

    /**
     * Sets the value of the breakDownPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setBreakDownPres(PressureMeasure value) {
        this.breakDownPres = value;
    }

    /**
     * Gets the value of the percentPad property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getPercentPad() {
        return percentPad;
    }

    /**
     * Sets the value of the percentPad property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setPercentPad(VolumePerVolumeMeasurePercent value) {
        this.percentPad = value;
    }

    /**
     * Gets the value of the fractureGradient property.
     * 
     * @return
     *     possible object is
     *     {@link ForcePerVolumeMeasure }
     *     
     */
    public ForcePerVolumeMeasure getFractureGradient() {
        return fractureGradient;
    }

    /**
     * Sets the value of the fractureGradient property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForcePerVolumeMeasure }
     *     
     */
    public void setFractureGradient(ForcePerVolumeMeasure value) {
        this.fractureGradient = value;
    }

    /**
     * Gets the value of the pipeFrictionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPipeFrictionFactor() {
        return pipeFrictionFactor;
    }

    /**
     * Sets the value of the pipeFrictionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPipeFrictionFactor(Double value) {
        this.pipeFrictionFactor = value;
    }

    /**
     * Gets the value of the stageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getStageCount() {
        return stageCount;
    }

    /**
     * Sets the value of the stageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setStageCount(Short value) {
        this.stageCount = value;
    }

    /**
     * Gets the value of the tubular property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tubular property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getTubular().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsStimTubular }
     * 
     * 
     */
    public List<CsStimTubular> getTubular() {
        if (tubular == null) {
            tubular = new ArrayList<CsStimTubular>();
        }
        return this.tubular;
    }

    /**
     * Gets the value of the jobStage property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobStage property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getJobStage().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsStimJobStage }
     * 
     * 
     */
    public List<CsStimJobStage> getJobStage() {
        if (jobStage == null) {
            jobStage = new ArrayList<CsStimJobStage>();
        }
        return this.jobStage;
    }

    /**
     * Gets the value of the jobEvent property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobEvent property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getJobEvent().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsStimEvent }
     * 
     * 
     */
    public List<CsStimEvent> getJobEvent() {
        if (jobEvent == null) {
            jobEvent = new ArrayList<CsStimEvent>();
        }
        return this.jobEvent;
    }

    /**
     * Gets the value of the extensionNameValue property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNameValue property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getExtensionNameValue().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsExtensionNameValue }
     * 
     * 
     */
    public List<CsExtensionNameValue> getExtensionNameValue() {
        if (extensionNameValue == null) {
            extensionNameValue = new ArrayList<CsExtensionNameValue>();
        }
        return this.extensionNameValue;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
