//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * In a step down pump diagnostics test, this item contains all 
 * 			the data for a particular step in that test.
 * 
 * <p>Java class for cs_stimTestStep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_stimTestStep">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="number" type="{http://www.witsml.org/schemas/1series}nonNegativeCount"/>
 *         <element name="bottomholeRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="pres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="pipeFriction" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="entryFriction" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="perfFriction" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="nearWellboreFriction" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="surfaceRate" type="{http://www.witsml.org/schemas/1series}volumeFlowRateMeasure" minOccurs="0"/>
 *         <element name="extensionNameValue" type="{http://www.witsml.org/schemas/1series}cs_extensionNameValue" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_uid"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_stimTestStep", propOrder = {
    "number",
    "bottomholeRate",
    "pres",
    "pipeFriction",
    "entryFriction",
    "perfFriction",
    "nearWellboreFriction",
    "surfaceRate",
    "extensionNameValue"
})
public class CsStimTestStep {

    protected short number;
    protected VolumeFlowRateMeasure bottomholeRate;
    protected PressureMeasure pres;
    protected PressureMeasure pipeFriction;
    protected PressureMeasure entryFriction;
    protected PressureMeasure perfFriction;
    protected PressureMeasure nearWellboreFriction;
    protected VolumeFlowRateMeasure surfaceRate;
    protected List<CsExtensionNameValue> extensionNameValue;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the number property.
     * 
     */
    public short getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(short value) {
        this.number = value;
    }

    /**
     * Gets the value of the bottomholeRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getBottomholeRate() {
        return bottomholeRate;
    }

    /**
     * Sets the value of the bottomholeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setBottomholeRate(VolumeFlowRateMeasure value) {
        this.bottomholeRate = value;
    }

    /**
     * Gets the value of the pres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPres() {
        return pres;
    }

    /**
     * Sets the value of the pres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPres(PressureMeasure value) {
        this.pres = value;
    }

    /**
     * Gets the value of the pipeFriction property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPipeFriction() {
        return pipeFriction;
    }

    /**
     * Sets the value of the pipeFriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPipeFriction(PressureMeasure value) {
        this.pipeFriction = value;
    }

    /**
     * Gets the value of the entryFriction property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getEntryFriction() {
        return entryFriction;
    }

    /**
     * Sets the value of the entryFriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setEntryFriction(PressureMeasure value) {
        this.entryFriction = value;
    }

    /**
     * Gets the value of the perfFriction property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getPerfFriction() {
        return perfFriction;
    }

    /**
     * Sets the value of the perfFriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setPerfFriction(PressureMeasure value) {
        this.perfFriction = value;
    }

    /**
     * Gets the value of the nearWellboreFriction property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getNearWellboreFriction() {
        return nearWellboreFriction;
    }

    /**
     * Sets the value of the nearWellboreFriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setNearWellboreFriction(PressureMeasure value) {
        this.nearWellboreFriction = value;
    }

    /**
     * Gets the value of the surfaceRate property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public VolumeFlowRateMeasure getSurfaceRate() {
        return surfaceRate;
    }

    /**
     * Sets the value of the surfaceRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeFlowRateMeasure }
     *     
     */
    public void setSurfaceRate(VolumeFlowRateMeasure value) {
        this.surfaceRate = value;
    }

    /**
     * Gets the value of the extensionNameValue property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNameValue property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getExtensionNameValue().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsExtensionNameValue }
     * 
     * 
     */
    public List<CsExtensionNameValue> getExtensionNameValue() {
        if (extensionNameValue == null) {
            extensionNameValue = new ArrayList<CsExtensionNameValue>();
        }
        return this.extensionNameValue;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
