//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Reservoir Interval Component Schema.
 * 
 * <p>Java class for cs_stimReservoirInterval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="cs_stimReservoirInterval">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="mdLithTop" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="mdLithBottom" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="lithFormationPermeability" type="{http://www.witsml.org/schemas/1series}permeabilityRockMeasure" minOccurs="0"/>
 *         <element name="lithYoungsModulus" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="lithPorePres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="lithNetPayThickness" type="{http://www.witsml.org/schemas/1series}lengthMeasure" minOccurs="0"/>
 *         <element name="lithName" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="mdGrossPayTop" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="mdGrossPayBottom" type="{http://www.witsml.org/schemas/1series}measuredDepthCoord" minOccurs="0"/>
 *         <element name="grossPayThickness" type="{http://www.witsml.org/schemas/1series}lengthMeasure" minOccurs="0"/>
 *         <element name="netPayThickness" type="{http://www.witsml.org/schemas/1series}lengthMeasure" minOccurs="0"/>
 *         <element name="netPayPorePres" type="{http://www.witsml.org/schemas/1series}pressureMeasure" minOccurs="0"/>
 *         <element name="netPayFluidCompressibility" type="{http://www.witsml.org/schemas/1series}compressibilityMeasure" minOccurs="0"/>
 *         <element name="netPayFluidViscosity" type="{http://www.witsml.org/schemas/1series}dynamicViscosityMeasure" minOccurs="0"/>
 *         <element name="netPayName" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="netPayFormationPermeability" type="{http://www.witsml.org/schemas/1series}permeabilityRockMeasure" minOccurs="0"/>
 *         <element name="lithPoissonsRatio" type="{http://www.witsml.org/schemas/1series}dimensionlessMeasure" minOccurs="0"/>
 *         <element name="netPayFormationPorosity" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="formationPermeability" type="{http://www.witsml.org/schemas/1series}permeabilityRockMeasure" minOccurs="0"/>
 *         <element name="formationPorosity" type="{http://www.witsml.org/schemas/1series}volumePerVolumeMeasurePercent" minOccurs="0"/>
 *         <element name="nameFormation" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="extensionNameValue" type="{http://www.witsml.org/schemas/1series}cs_extensionNameValue" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_uid"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cs_stimReservoirInterval", propOrder = {
    "mdLithTop",
    "mdLithBottom",
    "lithFormationPermeability",
    "lithYoungsModulus",
    "lithPorePres",
    "lithNetPayThickness",
    "lithName",
    "mdGrossPayTop",
    "mdGrossPayBottom",
    "grossPayThickness",
    "netPayThickness",
    "netPayPorePres",
    "netPayFluidCompressibility",
    "netPayFluidViscosity",
    "netPayName",
    "netPayFormationPermeability",
    "lithPoissonsRatio",
    "netPayFormationPorosity",
    "formationPermeability",
    "formationPorosity",
    "nameFormation",
    "extensionNameValue"
})
public class CsStimReservoirInterval {

    protected MeasuredDepthCoord mdLithTop;
    protected MeasuredDepthCoord mdLithBottom;
    protected PermeabilityRockMeasure lithFormationPermeability;
    protected PressureMeasure lithYoungsModulus;
    protected PressureMeasure lithPorePres;
    protected LengthMeasure lithNetPayThickness;
    protected String lithName;
    protected MeasuredDepthCoord mdGrossPayTop;
    protected MeasuredDepthCoord mdGrossPayBottom;
    protected LengthMeasure grossPayThickness;
    protected LengthMeasure netPayThickness;
    protected PressureMeasure netPayPorePres;
    protected CompressibilityMeasure netPayFluidCompressibility;
    protected DynamicViscosityMeasure netPayFluidViscosity;
    protected String netPayName;
    protected PermeabilityRockMeasure netPayFormationPermeability;
    protected DimensionlessMeasure lithPoissonsRatio;
    protected VolumePerVolumeMeasurePercent netPayFormationPorosity;
    protected PermeabilityRockMeasure formationPermeability;
    protected VolumePerVolumeMeasurePercent formationPorosity;
    protected String nameFormation;
    protected List<CsExtensionNameValue> extensionNameValue;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the mdLithTop property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdLithTop() {
        return mdLithTop;
    }

    /**
     * Sets the value of the mdLithTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdLithTop(MeasuredDepthCoord value) {
        this.mdLithTop = value;
    }

    /**
     * Gets the value of the mdLithBottom property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdLithBottom() {
        return mdLithBottom;
    }

    /**
     * Sets the value of the mdLithBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdLithBottom(MeasuredDepthCoord value) {
        this.mdLithBottom = value;
    }

    /**
     * Gets the value of the lithFormationPermeability property.
     * 
     * @return
     *     possible object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public PermeabilityRockMeasure getLithFormationPermeability() {
        return lithFormationPermeability;
    }

    /**
     * Sets the value of the lithFormationPermeability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public void setLithFormationPermeability(PermeabilityRockMeasure value) {
        this.lithFormationPermeability = value;
    }

    /**
     * Gets the value of the lithYoungsModulus property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getLithYoungsModulus() {
        return lithYoungsModulus;
    }

    /**
     * Sets the value of the lithYoungsModulus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setLithYoungsModulus(PressureMeasure value) {
        this.lithYoungsModulus = value;
    }

    /**
     * Gets the value of the lithPorePres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getLithPorePres() {
        return lithPorePres;
    }

    /**
     * Sets the value of the lithPorePres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setLithPorePres(PressureMeasure value) {
        this.lithPorePres = value;
    }

    /**
     * Gets the value of the lithNetPayThickness property.
     * 
     * @return
     *     possible object is
     *     {@link LengthMeasure }
     *     
     */
    public LengthMeasure getLithNetPayThickness() {
        return lithNetPayThickness;
    }

    /**
     * Sets the value of the lithNetPayThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthMeasure }
     *     
     */
    public void setLithNetPayThickness(LengthMeasure value) {
        this.lithNetPayThickness = value;
    }

    /**
     * Gets the value of the lithName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLithName() {
        return lithName;
    }

    /**
     * Sets the value of the lithName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLithName(String value) {
        this.lithName = value;
    }

    /**
     * Gets the value of the mdGrossPayTop property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdGrossPayTop() {
        return mdGrossPayTop;
    }

    /**
     * Sets the value of the mdGrossPayTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdGrossPayTop(MeasuredDepthCoord value) {
        this.mdGrossPayTop = value;
    }

    /**
     * Gets the value of the mdGrossPayBottom property.
     * 
     * @return
     *     possible object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public MeasuredDepthCoord getMdGrossPayBottom() {
        return mdGrossPayBottom;
    }

    /**
     * Sets the value of the mdGrossPayBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasuredDepthCoord }
     *     
     */
    public void setMdGrossPayBottom(MeasuredDepthCoord value) {
        this.mdGrossPayBottom = value;
    }

    /**
     * Gets the value of the grossPayThickness property.
     * 
     * @return
     *     possible object is
     *     {@link LengthMeasure }
     *     
     */
    public LengthMeasure getGrossPayThickness() {
        return grossPayThickness;
    }

    /**
     * Sets the value of the grossPayThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthMeasure }
     *     
     */
    public void setGrossPayThickness(LengthMeasure value) {
        this.grossPayThickness = value;
    }

    /**
     * Gets the value of the netPayThickness property.
     * 
     * @return
     *     possible object is
     *     {@link LengthMeasure }
     *     
     */
    public LengthMeasure getNetPayThickness() {
        return netPayThickness;
    }

    /**
     * Sets the value of the netPayThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthMeasure }
     *     
     */
    public void setNetPayThickness(LengthMeasure value) {
        this.netPayThickness = value;
    }

    /**
     * Gets the value of the netPayPorePres property.
     * 
     * @return
     *     possible object is
     *     {@link PressureMeasure }
     *     
     */
    public PressureMeasure getNetPayPorePres() {
        return netPayPorePres;
    }

    /**
     * Sets the value of the netPayPorePres property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureMeasure }
     *     
     */
    public void setNetPayPorePres(PressureMeasure value) {
        this.netPayPorePres = value;
    }

    /**
     * Gets the value of the netPayFluidCompressibility property.
     * 
     * @return
     *     possible object is
     *     {@link CompressibilityMeasure }
     *     
     */
    public CompressibilityMeasure getNetPayFluidCompressibility() {
        return netPayFluidCompressibility;
    }

    /**
     * Sets the value of the netPayFluidCompressibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompressibilityMeasure }
     *     
     */
    public void setNetPayFluidCompressibility(CompressibilityMeasure value) {
        this.netPayFluidCompressibility = value;
    }

    /**
     * Gets the value of the netPayFluidViscosity property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicViscosityMeasure }
     *     
     */
    public DynamicViscosityMeasure getNetPayFluidViscosity() {
        return netPayFluidViscosity;
    }

    /**
     * Sets the value of the netPayFluidViscosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicViscosityMeasure }
     *     
     */
    public void setNetPayFluidViscosity(DynamicViscosityMeasure value) {
        this.netPayFluidViscosity = value;
    }

    /**
     * Gets the value of the netPayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetPayName() {
        return netPayName;
    }

    /**
     * Sets the value of the netPayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetPayName(String value) {
        this.netPayName = value;
    }

    /**
     * Gets the value of the netPayFormationPermeability property.
     * 
     * @return
     *     possible object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public PermeabilityRockMeasure getNetPayFormationPermeability() {
        return netPayFormationPermeability;
    }

    /**
     * Sets the value of the netPayFormationPermeability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public void setNetPayFormationPermeability(PermeabilityRockMeasure value) {
        this.netPayFormationPermeability = value;
    }

    /**
     * Gets the value of the lithPoissonsRatio property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionlessMeasure }
     *     
     */
    public DimensionlessMeasure getLithPoissonsRatio() {
        return lithPoissonsRatio;
    }

    /**
     * Sets the value of the lithPoissonsRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionlessMeasure }
     *     
     */
    public void setLithPoissonsRatio(DimensionlessMeasure value) {
        this.lithPoissonsRatio = value;
    }

    /**
     * Gets the value of the netPayFormationPorosity property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getNetPayFormationPorosity() {
        return netPayFormationPorosity;
    }

    /**
     * Sets the value of the netPayFormationPorosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setNetPayFormationPorosity(VolumePerVolumeMeasurePercent value) {
        this.netPayFormationPorosity = value;
    }

    /**
     * Gets the value of the formationPermeability property.
     * 
     * @return
     *     possible object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public PermeabilityRockMeasure getFormationPermeability() {
        return formationPermeability;
    }

    /**
     * Sets the value of the formationPermeability property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermeabilityRockMeasure }
     *     
     */
    public void setFormationPermeability(PermeabilityRockMeasure value) {
        this.formationPermeability = value;
    }

    /**
     * Gets the value of the formationPorosity property.
     * 
     * @return
     *     possible object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public VolumePerVolumeMeasurePercent getFormationPorosity() {
        return formationPorosity;
    }

    /**
     * Sets the value of the formationPorosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumePerVolumeMeasurePercent }
     *     
     */
    public void setFormationPorosity(VolumePerVolumeMeasurePercent value) {
        this.formationPorosity = value;
    }

    /**
     * Gets the value of the nameFormation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFormation() {
        return nameFormation;
    }

    /**
     * Sets the value of the nameFormation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFormation(String value) {
        this.nameFormation = value;
    }

    /**
     * Gets the value of the extensionNameValue property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNameValue property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getExtensionNameValue().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsExtensionNameValue }
     * 
     * 
     */
    public List<CsExtensionNameValue> getExtensionNameValue() {
        if (extensionNameValue == null) {
            extensionNameValue = new ArrayList<CsExtensionNameValue>();
        }
        return this.extensionNameValue;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
