//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the singular change log data type.
 * 
 * <p>Java class for obj_changeLog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="obj_changeLog">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="nameWell" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="nameWellbore" type="{http://www.witsml.org/schemas/1series}nameString" minOccurs="0"/>
 *         <element name="nameObject" type="{http://www.witsml.org/schemas/1series}nameString"/>
 *         <element name="objectType" type="{http://www.witsml.org/schemas/1series}nameString"/>
 *         <group ref="{http://www.witsml.org/schemas/1series}grp_changeLog" minOccurs="0"/>
 *         <element name="commonData" type="{http://www.witsml.org/schemas/1series}cs_commonData" minOccurs="0"/>
 *         <element name="customData" type="{http://www.witsml.org/schemas/1series}cs_customData" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_objectUid"/>
 *       <attribute name="uidWell" type="{http://www.witsml.org/schemas/1series}uidString" />
 *       <attribute name="uidWellbore" type="{http://www.witsml.org/schemas/1series}uidString" />
 *       <attribute name="uidObject" use="required" type="{http://www.witsml.org/schemas/1series}uidString" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obj_changeLog", propOrder = {
    "nameWell",
    "nameWellbore",
    "nameObject",
    "objectType",
    "sourceName",
    "lastChangeType",
    "lastChangeInfo",
    "changeHistory",
    "commonData",
    "customData"
})
public class ObjChangeLog {

    protected String nameWell;
    protected String nameWellbore;
    @XmlElement(required = true)
    protected String nameObject;
    @XmlElement(required = true)
    protected String objectType;
    protected String sourceName;
    @XmlSchemaType(name = "string")
    protected String lastChangeType;
    protected String lastChangeInfo;
    protected List<CsChangeHistory> changeHistory;
    protected CsCommonData commonData;
    protected CsCustomData customData;
    @XmlAttribute(name = "uidWell")
    protected String uidWell;
    @XmlAttribute(name = "uidWellbore")
    protected String uidWellbore;
    @XmlAttribute(name = "uidObject", required = true)
    protected String uidObject;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the nameWell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameWell() {
        return nameWell;
    }

    /**
     * Sets the value of the nameWell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameWell(String value) {
        this.nameWell = value;
    }

    /**
     * Gets the value of the nameWellbore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameWellbore() {
        return nameWellbore;
    }

    /**
     * Sets the value of the nameWellbore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameWellbore(String value) {
        this.nameWellbore = value;
    }

    /**
     * Gets the value of the nameObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameObject() {
        return nameObject;
    }

    /**
     * Sets the value of the nameObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameObject(String value) {
        this.nameObject = value;
    }

    /**
     * Gets the value of the objectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * Sets the value of the objectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectType(String value) {
        this.objectType = value;
    }

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the lastChangeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastChangeType() {
        return lastChangeType;
    }

    /**
     * Sets the value of the lastChangeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastChangeType(String value) {
        this.lastChangeType = value;
    }

    /**
     * Gets the value of the lastChangeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastChangeInfo() {
        return lastChangeInfo;
    }

    /**
     * Sets the value of the lastChangeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastChangeInfo(String value) {
        this.lastChangeInfo = value;
    }

    /**
     * Gets the value of the changeHistory property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeHistory property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getChangeHistory().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsChangeHistory }
     * 
     * 
     */
    public List<CsChangeHistory> getChangeHistory() {
        if (changeHistory == null) {
            changeHistory = new ArrayList<CsChangeHistory>();
        }
        return this.changeHistory;
    }

    /**
     * Gets the value of the commonData property.
     * 
     * @return
     *     possible object is
     *     {@link CsCommonData }
     *     
     */
    public CsCommonData getCommonData() {
        return commonData;
    }

    /**
     * Sets the value of the commonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsCommonData }
     *     
     */
    public void setCommonData(CsCommonData value) {
        this.commonData = value;
    }

    /**
     * Gets the value of the customData property.
     * 
     * @return
     *     possible object is
     *     {@link CsCustomData }
     *     
     */
    public CsCustomData getCustomData() {
        return customData;
    }

    /**
     * Sets the value of the customData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsCustomData }
     *     
     */
    public void setCustomData(CsCustomData value) {
        this.customData = value;
    }

    /**
     * Gets the value of the uidWell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidWell() {
        return uidWell;
    }

    /**
     * Sets the value of the uidWell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidWell(String value) {
        this.uidWell = value;
    }

    /**
     * Gets the value of the uidWellbore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidWellbore() {
        return uidWellbore;
    }

    /**
     * Sets the value of the uidWellbore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidWellbore(String value) {
        this.uidWellbore = value;
    }

    /**
     * Gets the value of the uidObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidObject() {
        return uidObject;
    }

    /**
     * Sets the value of the uidObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidObject(String value) {
        this.uidObject = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
