//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 03:00:38 PM CDT 
//


package com.hashmapinc.tempus.WitsmlObjects.v1411;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for obj_drillReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre> {@code
 * <complexType name="obj_drillReport">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="nameWell" type="{http://www.witsml.org/schemas/1series}nameString"/>
 *         <element name="nameWellbore" type="{http://www.witsml.org/schemas/1series}nameString"/>
 *         <element name="name" type="{http://www.witsml.org/schemas/1series}nameString"/>
 *         <group ref="{http://www.witsml.org/schemas/1series}grp_drillReport" minOccurs="0"/>
 *         <element name="commonData" type="{http://www.witsml.org/schemas/1series}cs_commonData" minOccurs="0"/>
 *         <element name="customData" type="{http://www.witsml.org/schemas/1series}cs_customData" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{http://www.witsml.org/schemas/1series}attgrp_objectUid"/>
 *       <attribute name="uidWell" type="{http://www.witsml.org/schemas/1series}uidParentString" />
 *       <attribute name="uidWellbore" type="{http://www.witsml.org/schemas/1series}uidParentString" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * } </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obj_drillReport", propOrder = {
    "nameWell",
    "nameWellbore",
    "name",
    "dTimStart",
    "dTimEnd",
    "versionKind",
    "createDate",
    "wellAlias",
    "wellboreAlias",
    "wellDatum",
    "wellCRS",
    "wellboreInfo",
    "statusInfo",
    "bitRecord",
    "fluid",
    "porePressure",
    "extendedReport",
    "surveyStation",
    "activity",
    "logInfo",
    "coreInfo",
    "wellTestInfo",
    "formTestInfo",
    "lithShowInfo",
    "equipFailureInfo",
    "controlIncidentInfo",
    "stratInfo",
    "perfInfo",
    "gasReadingInfo",
    "commonData",
    "customData"
})
public class ObjDrillReport {

    @XmlElement(required = true)
    protected String nameWell;
    @XmlElement(required = true)
    protected String nameWellbore;
    @XmlElement(required = true)
    protected String name;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dTimStart;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dTimEnd;
    @XmlSchemaType(name = "string")
    protected String versionKind;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDate;
    protected CsWellAlias wellAlias;
    protected List<CsWellAlias> wellboreAlias;
    protected List<CsWellDatum> wellDatum;
    protected List<CsWellCRS> wellCRS;
    protected CsDrillReportWellboreInfo wellboreInfo;
    protected List<CsDrillReportStatusInfo> statusInfo;
    protected List<CsBitRecord> bitRecord;
    protected List<CsFluid> fluid;
    protected List<CsDrillReportPorePressure> porePressure;
    protected TimestampedCommentString extendedReport;
    protected List<CsDrillReportSurveyStation> surveyStation;
    protected List<CsActivity> activity;
    protected List<CsDrillReportLogInfo> logInfo;
    protected List<CsDrillReportCoreInfo> coreInfo;
    protected List<CsDrillReportWellTestInfo> wellTestInfo;
    protected List<CsDrillReportFormTestInfo> formTestInfo;
    protected List<CsDrillReportLithShowInfo> lithShowInfo;
    protected List<CsDrillReportEquipFailureInfo> equipFailureInfo;
    protected List<CsDrillReportControlIncidentInfo> controlIncidentInfo;
    protected List<CsDrillReportStratInfo> stratInfo;
    protected List<CsDrillReportPerfInfo> perfInfo;
    protected List<CsDrillReportGasReadingInfo> gasReadingInfo;
    protected CsCommonData commonData;
    protected CsCustomData customData;
    @XmlAttribute(name = "uidWell")
    protected String uidWell;
    @XmlAttribute(name = "uidWellbore")
    protected String uidWellbore;
    @XmlAttribute(name = "uid")
    protected String uid;

    /**
     * Gets the value of the nameWell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameWell() {
        return nameWell;
    }

    /**
     * Sets the value of the nameWell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameWell(String value) {
        this.nameWell = value;
    }

    /**
     * Gets the value of the nameWellbore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameWellbore() {
        return nameWellbore;
    }

    /**
     * Sets the value of the nameWellbore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameWellbore(String value) {
        this.nameWellbore = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dTimStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDTimStart() {
        return dTimStart;
    }

    /**
     * Sets the value of the dTimStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDTimStart(XMLGregorianCalendar value) {
        this.dTimStart = value;
    }

    /**
     * Gets the value of the dTimEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDTimEnd() {
        return dTimEnd;
    }

    /**
     * Sets the value of the dTimEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDTimEnd(XMLGregorianCalendar value) {
        this.dTimEnd = value;
    }

    /**
     * Gets the value of the versionKind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionKind() {
        return versionKind;
    }

    /**
     * Sets the value of the versionKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionKind(String value) {
        this.versionKind = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDate(XMLGregorianCalendar value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the wellAlias property.
     * 
     * @return
     *     possible object is
     *     {@link CsWellAlias }
     *     
     */
    public CsWellAlias getWellAlias() {
        return wellAlias;
    }

    /**
     * Sets the value of the wellAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsWellAlias }
     *     
     */
    public void setWellAlias(CsWellAlias value) {
        this.wellAlias = value;
    }

    /**
     * Gets the value of the wellboreAlias property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wellboreAlias property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getWellboreAlias().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsWellAlias }
     * 
     * 
     */
    public List<CsWellAlias> getWellboreAlias() {
        if (wellboreAlias == null) {
            wellboreAlias = new ArrayList<CsWellAlias>();
        }
        return this.wellboreAlias;
    }

    /**
     * Gets the value of the wellDatum property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wellDatum property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getWellDatum().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsWellDatum }
     * 
     * 
     */
    public List<CsWellDatum> getWellDatum() {
        if (wellDatum == null) {
            wellDatum = new ArrayList<CsWellDatum>();
        }
        return this.wellDatum;
    }

    /**
     * Gets the value of the wellCRS property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wellCRS property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getWellCRS().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsWellCRS }
     * 
     * 
     */
    public List<CsWellCRS> getWellCRS() {
        if (wellCRS == null) {
            wellCRS = new ArrayList<CsWellCRS>();
        }
        return this.wellCRS;
    }

    /**
     * Gets the value of the wellboreInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CsDrillReportWellboreInfo }
     *     
     */
    public CsDrillReportWellboreInfo getWellboreInfo() {
        return wellboreInfo;
    }

    /**
     * Sets the value of the wellboreInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsDrillReportWellboreInfo }
     *     
     */
    public void setWellboreInfo(CsDrillReportWellboreInfo value) {
        this.wellboreInfo = value;
    }

    /**
     * Gets the value of the statusInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getStatusInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportStatusInfo }
     * 
     * 
     */
    public List<CsDrillReportStatusInfo> getStatusInfo() {
        if (statusInfo == null) {
            statusInfo = new ArrayList<CsDrillReportStatusInfo>();
        }
        return this.statusInfo;
    }

    /**
     * Gets the value of the bitRecord property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bitRecord property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getBitRecord().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsBitRecord }
     * 
     * 
     */
    public List<CsBitRecord> getBitRecord() {
        if (bitRecord == null) {
            bitRecord = new ArrayList<CsBitRecord>();
        }
        return this.bitRecord;
    }

    /**
     * Gets the value of the fluid property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fluid property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getFluid().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsFluid }
     * 
     * 
     */
    public List<CsFluid> getFluid() {
        if (fluid == null) {
            fluid = new ArrayList<CsFluid>();
        }
        return this.fluid;
    }

    /**
     * Gets the value of the porePressure property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the porePressure property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getPorePressure().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportPorePressure }
     * 
     * 
     */
    public List<CsDrillReportPorePressure> getPorePressure() {
        if (porePressure == null) {
            porePressure = new ArrayList<CsDrillReportPorePressure>();
        }
        return this.porePressure;
    }

    /**
     * Gets the value of the extendedReport property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampedCommentString }
     *     
     */
    public TimestampedCommentString getExtendedReport() {
        return extendedReport;
    }

    /**
     * Sets the value of the extendedReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampedCommentString }
     *     
     */
    public void setExtendedReport(TimestampedCommentString value) {
        this.extendedReport = value;
    }

    /**
     * Gets the value of the surveyStation property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the surveyStation property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getSurveyStation().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportSurveyStation }
     * 
     * 
     */
    public List<CsDrillReportSurveyStation> getSurveyStation() {
        if (surveyStation == null) {
            surveyStation = new ArrayList<CsDrillReportSurveyStation>();
        }
        return this.surveyStation;
    }

    /**
     * Gets the value of the activity property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getActivity().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsActivity }
     * 
     * 
     */
    public List<CsActivity> getActivity() {
        if (activity == null) {
            activity = new ArrayList<CsActivity>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the logInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getLogInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportLogInfo }
     * 
     * 
     */
    public List<CsDrillReportLogInfo> getLogInfo() {
        if (logInfo == null) {
            logInfo = new ArrayList<CsDrillReportLogInfo>();
        }
        return this.logInfo;
    }

    /**
     * Gets the value of the coreInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coreInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getCoreInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportCoreInfo }
     * 
     * 
     */
    public List<CsDrillReportCoreInfo> getCoreInfo() {
        if (coreInfo == null) {
            coreInfo = new ArrayList<CsDrillReportCoreInfo>();
        }
        return this.coreInfo;
    }

    /**
     * Gets the value of the wellTestInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wellTestInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getWellTestInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportWellTestInfo }
     * 
     * 
     */
    public List<CsDrillReportWellTestInfo> getWellTestInfo() {
        if (wellTestInfo == null) {
            wellTestInfo = new ArrayList<CsDrillReportWellTestInfo>();
        }
        return this.wellTestInfo;
    }

    /**
     * Gets the value of the formTestInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formTestInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getFormTestInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportFormTestInfo }
     * 
     * 
     */
    public List<CsDrillReportFormTestInfo> getFormTestInfo() {
        if (formTestInfo == null) {
            formTestInfo = new ArrayList<CsDrillReportFormTestInfo>();
        }
        return this.formTestInfo;
    }

    /**
     * Gets the value of the lithShowInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lithShowInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getLithShowInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportLithShowInfo }
     * 
     * 
     */
    public List<CsDrillReportLithShowInfo> getLithShowInfo() {
        if (lithShowInfo == null) {
            lithShowInfo = new ArrayList<CsDrillReportLithShowInfo>();
        }
        return this.lithShowInfo;
    }

    /**
     * Gets the value of the equipFailureInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipFailureInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getEquipFailureInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportEquipFailureInfo }
     * 
     * 
     */
    public List<CsDrillReportEquipFailureInfo> getEquipFailureInfo() {
        if (equipFailureInfo == null) {
            equipFailureInfo = new ArrayList<CsDrillReportEquipFailureInfo>();
        }
        return this.equipFailureInfo;
    }

    /**
     * Gets the value of the controlIncidentInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controlIncidentInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getControlIncidentInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportControlIncidentInfo }
     * 
     * 
     */
    public List<CsDrillReportControlIncidentInfo> getControlIncidentInfo() {
        if (controlIncidentInfo == null) {
            controlIncidentInfo = new ArrayList<CsDrillReportControlIncidentInfo>();
        }
        return this.controlIncidentInfo;
    }

    /**
     * Gets the value of the stratInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stratInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getStratInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportStratInfo }
     * 
     * 
     */
    public List<CsDrillReportStratInfo> getStratInfo() {
        if (stratInfo == null) {
            stratInfo = new ArrayList<CsDrillReportStratInfo>();
        }
        return this.stratInfo;
    }

    /**
     * Gets the value of the perfInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the perfInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getPerfInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportPerfInfo }
     * 
     * 
     */
    public List<CsDrillReportPerfInfo> getPerfInfo() {
        if (perfInfo == null) {
            perfInfo = new ArrayList<CsDrillReportPerfInfo>();
        }
        return this.perfInfo;
    }

    /**
     * Gets the value of the gasReadingInfo property.
     * 
     *
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gasReadingInfo property.
     * 
     *
     * For example, to add a new item, do as follows:
     * <pre> {@code
     *    getGasReadingInfo().add(newItem);
     * } </pre>
     * 
     * 
     *
     * Objects of the following type(s) are allowed in the list
     * {@link CsDrillReportGasReadingInfo }
     * 
     * 
     */
    public List<CsDrillReportGasReadingInfo> getGasReadingInfo() {
        if (gasReadingInfo == null) {
            gasReadingInfo = new ArrayList<CsDrillReportGasReadingInfo>();
        }
        return this.gasReadingInfo;
    }

    /**
     * Gets the value of the commonData property.
     * 
     * @return
     *     possible object is
     *     {@link CsCommonData }
     *     
     */
    public CsCommonData getCommonData() {
        return commonData;
    }

    /**
     * Sets the value of the commonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsCommonData }
     *     
     */
    public void setCommonData(CsCommonData value) {
        this.commonData = value;
    }

    /**
     * Gets the value of the customData property.
     * 
     * @return
     *     possible object is
     *     {@link CsCustomData }
     *     
     */
    public CsCustomData getCustomData() {
        return customData;
    }

    /**
     * Sets the value of the customData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsCustomData }
     *     
     */
    public void setCustomData(CsCustomData value) {
        this.customData = value;
    }

    /**
     * Gets the value of the uidWell property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidWell() {
        return uidWell;
    }

    /**
     * Sets the value of the uidWell property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidWell(String value) {
        this.uidWell = value;
    }

    /**
     * Gets the value of the uidWellbore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidWellbore() {
        return uidWellbore;
    }

    /**
     * Sets the value of the uidWellbore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidWellbore(String value) {
        this.uidWellbore = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

}
